/*
BriskStack Platform API

Testing AiGatewayChatAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package briskstack

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/briskstack"
)

func Test_briskstack_AiGatewayChatAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AiGatewayChatAPIService AiGatewayV1ChatCompletionsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AiGatewayChatAPI.AiGatewayV1ChatCompletionsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
