/*
BriskStack Platform API

Testing HelloWorldCoreAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package briskstackplatform

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/briskstack/platform-sdk-go"
)

func Test_briskstackplatform_HelloWorldCoreAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HelloWorldCoreAPIService HelloWorldV1Get", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.HelloWorldCoreAPI.HelloWorldV1Get(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
