/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type AiGatewayChatAPI interface {

	/*
	AiGatewayV1ChatCompletionsPost Create chat completion

	Creates a chat completion using AI providers via Cloudflare AI Gateway. Supports BYOK (Bring Your Own Key) - pass your AI provider API key in the X-API-Key header.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAiGatewayV1ChatCompletionsPostRequest
	*/
	AiGatewayV1ChatCompletionsPost(ctx context.Context) ApiAiGatewayV1ChatCompletionsPostRequest

	// AiGatewayV1ChatCompletionsPostExecute executes the request
	//  @return AiGatewayChatCompletionResponse
	AiGatewayV1ChatCompletionsPostExecute(r ApiAiGatewayV1ChatCompletionsPostRequest) (*AiGatewayChatCompletionResponse, *http.Response, error)
}

// AiGatewayChatAPIService AiGatewayChatAPI service
type AiGatewayChatAPIService service

type ApiAiGatewayV1ChatCompletionsPostRequest struct {
	ctx context.Context
	ApiService AiGatewayChatAPI
	aiGatewayChatCompletionRequest *AiGatewayChatCompletionRequest
}

func (r ApiAiGatewayV1ChatCompletionsPostRequest) AiGatewayChatCompletionRequest(aiGatewayChatCompletionRequest AiGatewayChatCompletionRequest) ApiAiGatewayV1ChatCompletionsPostRequest {
	r.aiGatewayChatCompletionRequest = &aiGatewayChatCompletionRequest
	return r
}

func (r ApiAiGatewayV1ChatCompletionsPostRequest) Execute() (*AiGatewayChatCompletionResponse, *http.Response, error) {
	return r.ApiService.AiGatewayV1ChatCompletionsPostExecute(r)
}

/*
AiGatewayV1ChatCompletionsPost Create chat completion

Creates a chat completion using AI providers via Cloudflare AI Gateway. Supports BYOK (Bring Your Own Key) - pass your AI provider API key in the X-API-Key header.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAiGatewayV1ChatCompletionsPostRequest
*/
func (a *AiGatewayChatAPIService) AiGatewayV1ChatCompletionsPost(ctx context.Context) ApiAiGatewayV1ChatCompletionsPostRequest {
	return ApiAiGatewayV1ChatCompletionsPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return AiGatewayChatCompletionResponse
func (a *AiGatewayChatAPIService) AiGatewayV1ChatCompletionsPostExecute(r ApiAiGatewayV1ChatCompletionsPostRequest) (*AiGatewayChatCompletionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AiGatewayChatCompletionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AiGatewayChatAPIService.AiGatewayV1ChatCompletionsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/ai-gateway/v1/chat/completions"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.aiGatewayChatCompletionRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v AiGatewayErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v AiGatewayErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v AiGatewayErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v AiGatewayErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 502 {
			var v AiGatewayErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
