/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type HelloWorldMessagesAPI interface {

	/*
	HelloWorldV1MessagesPost Create message

	Creates a new message

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiHelloWorldV1MessagesPostRequest
	*/
	HelloWorldV1MessagesPost(ctx context.Context) ApiHelloWorldV1MessagesPostRequest

	// HelloWorldV1MessagesPostExecute executes the request
	//  @return HelloWorldCreateMessageResponse
	HelloWorldV1MessagesPostExecute(r ApiHelloWorldV1MessagesPostRequest) (*HelloWorldCreateMessageResponse, *http.Response, error)
}

// HelloWorldMessagesAPIService HelloWorldMessagesAPI service
type HelloWorldMessagesAPIService service

type ApiHelloWorldV1MessagesPostRequest struct {
	ctx context.Context
	ApiService HelloWorldMessagesAPI
	helloWorldCreateMessageRequest *HelloWorldCreateMessageRequest
}

func (r ApiHelloWorldV1MessagesPostRequest) HelloWorldCreateMessageRequest(helloWorldCreateMessageRequest HelloWorldCreateMessageRequest) ApiHelloWorldV1MessagesPostRequest {
	r.helloWorldCreateMessageRequest = &helloWorldCreateMessageRequest
	return r
}

func (r ApiHelloWorldV1MessagesPostRequest) Execute() (*HelloWorldCreateMessageResponse, *http.Response, error) {
	return r.ApiService.HelloWorldV1MessagesPostExecute(r)
}

/*
HelloWorldV1MessagesPost Create message

Creates a new message

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiHelloWorldV1MessagesPostRequest
*/
func (a *HelloWorldMessagesAPIService) HelloWorldV1MessagesPost(ctx context.Context) ApiHelloWorldV1MessagesPostRequest {
	return ApiHelloWorldV1MessagesPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return HelloWorldCreateMessageResponse
func (a *HelloWorldMessagesAPIService) HelloWorldV1MessagesPostExecute(r ApiHelloWorldV1MessagesPostRequest) (*HelloWorldCreateMessageResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *HelloWorldCreateMessageResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "HelloWorldMessagesAPIService.HelloWorldV1MessagesPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/hello-world/v1/messages"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.helloWorldCreateMessageRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HelloWorldErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
