/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstackplatform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AiGatewayChatCompletionResponseChoicesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiGatewayChatCompletionResponseChoicesInner{}

// AiGatewayChatCompletionResponseChoicesInner struct for AiGatewayChatCompletionResponseChoicesInner
type AiGatewayChatCompletionResponseChoicesInner struct {
	Index int32 `json:"index"`
	Message AiGatewayChatMessage `json:"message"`
	FinishReason string `json:"finish_reason"`
	Logprobs interface{} `json:"logprobs,omitempty"`
}

type _AiGatewayChatCompletionResponseChoicesInner AiGatewayChatCompletionResponseChoicesInner

// NewAiGatewayChatCompletionResponseChoicesInner instantiates a new AiGatewayChatCompletionResponseChoicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiGatewayChatCompletionResponseChoicesInner(index int32, message AiGatewayChatMessage, finishReason string) *AiGatewayChatCompletionResponseChoicesInner {
	this := AiGatewayChatCompletionResponseChoicesInner{}
	this.Index = index
	this.Message = message
	this.FinishReason = finishReason
	return &this
}

// NewAiGatewayChatCompletionResponseChoicesInnerWithDefaults instantiates a new AiGatewayChatCompletionResponseChoicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiGatewayChatCompletionResponseChoicesInnerWithDefaults() *AiGatewayChatCompletionResponseChoicesInner {
	this := AiGatewayChatCompletionResponseChoicesInner{}
	return &this
}

// GetIndex returns the Index field value
func (o *AiGatewayChatCompletionResponseChoicesInner) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponseChoicesInner) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *AiGatewayChatCompletionResponseChoicesInner) SetIndex(v int32) {
	o.Index = v
}

// GetMessage returns the Message field value
func (o *AiGatewayChatCompletionResponseChoicesInner) GetMessage() AiGatewayChatMessage {
	if o == nil {
		var ret AiGatewayChatMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponseChoicesInner) GetMessageOk() (*AiGatewayChatMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *AiGatewayChatCompletionResponseChoicesInner) SetMessage(v AiGatewayChatMessage) {
	o.Message = v
}

// GetFinishReason returns the FinishReason field value
func (o *AiGatewayChatCompletionResponseChoicesInner) GetFinishReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FinishReason
}

// GetFinishReasonOk returns a tuple with the FinishReason field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponseChoicesInner) GetFinishReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FinishReason, true
}

// SetFinishReason sets field value
func (o *AiGatewayChatCompletionResponseChoicesInner) SetFinishReason(v string) {
	o.FinishReason = v
}

// GetLogprobs returns the Logprobs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiGatewayChatCompletionResponseChoicesInner) GetLogprobs() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Logprobs
}

// GetLogprobsOk returns a tuple with the Logprobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiGatewayChatCompletionResponseChoicesInner) GetLogprobsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Logprobs) {
		return nil, false
	}
	return &o.Logprobs, true
}

// HasLogprobs returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionResponseChoicesInner) HasLogprobs() bool {
	if o != nil && !IsNil(o.Logprobs) {
		return true
	}

	return false
}

// SetLogprobs gets a reference to the given interface{} and assigns it to the Logprobs field.
func (o *AiGatewayChatCompletionResponseChoicesInner) SetLogprobs(v interface{}) {
	o.Logprobs = v
}

func (o AiGatewayChatCompletionResponseChoicesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiGatewayChatCompletionResponseChoicesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index"] = o.Index
	toSerialize["message"] = o.Message
	toSerialize["finish_reason"] = o.FinishReason
	if o.Logprobs != nil {
		toSerialize["logprobs"] = o.Logprobs
	}
	return toSerialize, nil
}

func (o *AiGatewayChatCompletionResponseChoicesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
		"message",
		"finish_reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAiGatewayChatCompletionResponseChoicesInner := _AiGatewayChatCompletionResponseChoicesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAiGatewayChatCompletionResponseChoicesInner)

	if err != nil {
		return err
	}

	*o = AiGatewayChatCompletionResponseChoicesInner(varAiGatewayChatCompletionResponseChoicesInner)

	return err
}

type NullableAiGatewayChatCompletionResponseChoicesInner struct {
	value *AiGatewayChatCompletionResponseChoicesInner
	isSet bool
}

func (v NullableAiGatewayChatCompletionResponseChoicesInner) Get() *AiGatewayChatCompletionResponseChoicesInner {
	return v.value
}

func (v *NullableAiGatewayChatCompletionResponseChoicesInner) Set(val *AiGatewayChatCompletionResponseChoicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAiGatewayChatCompletionResponseChoicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAiGatewayChatCompletionResponseChoicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiGatewayChatCompletionResponseChoicesInner(val *AiGatewayChatCompletionResponseChoicesInner) *NullableAiGatewayChatCompletionResponseChoicesInner {
	return &NullableAiGatewayChatCompletionResponseChoicesInner{value: val, isSet: true}
}

func (v NullableAiGatewayChatCompletionResponseChoicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiGatewayChatCompletionResponseChoicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


