/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AiGatewayChatCompletionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiGatewayChatCompletionResponse{}

// AiGatewayChatCompletionResponse struct for AiGatewayChatCompletionResponse
type AiGatewayChatCompletionResponse struct {
	Id string `json:"id"`
	Object string `json:"object"`
	Created int32 `json:"created"`
	Model string `json:"model"`
	Choices []AiGatewayChatCompletionResponseChoicesInner `json:"choices"`
	Usage *AiGatewayChatCompletionResponseUsage `json:"usage,omitempty"`
	SystemFingerprint *string `json:"system_fingerprint,omitempty"`
}

type _AiGatewayChatCompletionResponse AiGatewayChatCompletionResponse

// NewAiGatewayChatCompletionResponse instantiates a new AiGatewayChatCompletionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiGatewayChatCompletionResponse(id string, object string, created int32, model string, choices []AiGatewayChatCompletionResponseChoicesInner) *AiGatewayChatCompletionResponse {
	this := AiGatewayChatCompletionResponse{}
	this.Id = id
	this.Object = object
	this.Created = created
	this.Model = model
	this.Choices = choices
	return &this
}

// NewAiGatewayChatCompletionResponseWithDefaults instantiates a new AiGatewayChatCompletionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiGatewayChatCompletionResponseWithDefaults() *AiGatewayChatCompletionResponse {
	this := AiGatewayChatCompletionResponse{}
	return &this
}

// GetId returns the Id field value
func (o *AiGatewayChatCompletionResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AiGatewayChatCompletionResponse) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value
func (o *AiGatewayChatCompletionResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *AiGatewayChatCompletionResponse) SetObject(v string) {
	o.Object = v
}

// GetCreated returns the Created field value
func (o *AiGatewayChatCompletionResponse) GetCreated() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponse) GetCreatedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *AiGatewayChatCompletionResponse) SetCreated(v int32) {
	o.Created = v
}

// GetModel returns the Model field value
func (o *AiGatewayChatCompletionResponse) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponse) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *AiGatewayChatCompletionResponse) SetModel(v string) {
	o.Model = v
}

// GetChoices returns the Choices field value
func (o *AiGatewayChatCompletionResponse) GetChoices() []AiGatewayChatCompletionResponseChoicesInner {
	if o == nil {
		var ret []AiGatewayChatCompletionResponseChoicesInner
		return ret
	}

	return o.Choices
}

// GetChoicesOk returns a tuple with the Choices field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponse) GetChoicesOk() ([]AiGatewayChatCompletionResponseChoicesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Choices, true
}

// SetChoices sets field value
func (o *AiGatewayChatCompletionResponse) SetChoices(v []AiGatewayChatCompletionResponseChoicesInner) {
	o.Choices = v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionResponse) GetUsage() AiGatewayChatCompletionResponseUsage {
	if o == nil || IsNil(o.Usage) {
		var ret AiGatewayChatCompletionResponseUsage
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponse) GetUsageOk() (*AiGatewayChatCompletionResponseUsage, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionResponse) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given AiGatewayChatCompletionResponseUsage and assigns it to the Usage field.
func (o *AiGatewayChatCompletionResponse) SetUsage(v AiGatewayChatCompletionResponseUsage) {
	o.Usage = &v
}

// GetSystemFingerprint returns the SystemFingerprint field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionResponse) GetSystemFingerprint() string {
	if o == nil || IsNil(o.SystemFingerprint) {
		var ret string
		return ret
	}
	return *o.SystemFingerprint
}

// GetSystemFingerprintOk returns a tuple with the SystemFingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponse) GetSystemFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.SystemFingerprint) {
		return nil, false
	}
	return o.SystemFingerprint, true
}

// HasSystemFingerprint returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionResponse) HasSystemFingerprint() bool {
	if o != nil && !IsNil(o.SystemFingerprint) {
		return true
	}

	return false
}

// SetSystemFingerprint gets a reference to the given string and assigns it to the SystemFingerprint field.
func (o *AiGatewayChatCompletionResponse) SetSystemFingerprint(v string) {
	o.SystemFingerprint = &v
}

func (o AiGatewayChatCompletionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiGatewayChatCompletionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["object"] = o.Object
	toSerialize["created"] = o.Created
	toSerialize["model"] = o.Model
	toSerialize["choices"] = o.Choices
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	if !IsNil(o.SystemFingerprint) {
		toSerialize["system_fingerprint"] = o.SystemFingerprint
	}
	return toSerialize, nil
}

func (o *AiGatewayChatCompletionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"object",
		"created",
		"model",
		"choices",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAiGatewayChatCompletionResponse := _AiGatewayChatCompletionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAiGatewayChatCompletionResponse)

	if err != nil {
		return err
	}

	*o = AiGatewayChatCompletionResponse(varAiGatewayChatCompletionResponse)

	return err
}

type NullableAiGatewayChatCompletionResponse struct {
	value *AiGatewayChatCompletionResponse
	isSet bool
}

func (v NullableAiGatewayChatCompletionResponse) Get() *AiGatewayChatCompletionResponse {
	return v.value
}

func (v *NullableAiGatewayChatCompletionResponse) Set(val *AiGatewayChatCompletionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAiGatewayChatCompletionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAiGatewayChatCompletionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiGatewayChatCompletionResponse(val *AiGatewayChatCompletionResponse) *NullableAiGatewayChatCompletionResponse {
	return &NullableAiGatewayChatCompletionResponse{value: val, isSet: true}
}

func (v NullableAiGatewayChatCompletionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiGatewayChatCompletionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


