/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstackplatform

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the HelloWorldHealthzResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelloWorldHealthzResponse{}

// HelloWorldHealthzResponse struct for HelloWorldHealthzResponse
type HelloWorldHealthzResponse struct {
	// Health status indicator
	Status string `json:"status"`
	// Service name
	Service string `json:"service"`
	// Deployment environment
	Environment string `json:"environment"`
	// Service version
	Version string `json:"version"`
	// Current server time in ISO 8601 format
	Timestamp time.Time `json:"timestamp"`
	// Service uptime in seconds (if available)
	Uptime *float32 `json:"uptime,omitempty"`
}

type _HelloWorldHealthzResponse HelloWorldHealthzResponse

// NewHelloWorldHealthzResponse instantiates a new HelloWorldHealthzResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelloWorldHealthzResponse(status string, service string, environment string, version string, timestamp time.Time) *HelloWorldHealthzResponse {
	this := HelloWorldHealthzResponse{}
	this.Status = status
	this.Service = service
	this.Environment = environment
	this.Version = version
	this.Timestamp = timestamp
	return &this
}

// NewHelloWorldHealthzResponseWithDefaults instantiates a new HelloWorldHealthzResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelloWorldHealthzResponseWithDefaults() *HelloWorldHealthzResponse {
	this := HelloWorldHealthzResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *HelloWorldHealthzResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HelloWorldHealthzResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HelloWorldHealthzResponse) SetStatus(v string) {
	o.Status = v
}

// GetService returns the Service field value
func (o *HelloWorldHealthzResponse) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *HelloWorldHealthzResponse) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *HelloWorldHealthzResponse) SetService(v string) {
	o.Service = v
}

// GetEnvironment returns the Environment field value
func (o *HelloWorldHealthzResponse) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *HelloWorldHealthzResponse) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *HelloWorldHealthzResponse) SetEnvironment(v string) {
	o.Environment = v
}

// GetVersion returns the Version field value
func (o *HelloWorldHealthzResponse) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *HelloWorldHealthzResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *HelloWorldHealthzResponse) SetVersion(v string) {
	o.Version = v
}

// GetTimestamp returns the Timestamp field value
func (o *HelloWorldHealthzResponse) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *HelloWorldHealthzResponse) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *HelloWorldHealthzResponse) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetUptime returns the Uptime field value if set, zero value otherwise.
func (o *HelloWorldHealthzResponse) GetUptime() float32 {
	if o == nil || IsNil(o.Uptime) {
		var ret float32
		return ret
	}
	return *o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelloWorldHealthzResponse) GetUptimeOk() (*float32, bool) {
	if o == nil || IsNil(o.Uptime) {
		return nil, false
	}
	return o.Uptime, true
}

// HasUptime returns a boolean if a field has been set.
func (o *HelloWorldHealthzResponse) HasUptime() bool {
	if o != nil && !IsNil(o.Uptime) {
		return true
	}

	return false
}

// SetUptime gets a reference to the given float32 and assigns it to the Uptime field.
func (o *HelloWorldHealthzResponse) SetUptime(v float32) {
	o.Uptime = &v
}

func (o HelloWorldHealthzResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelloWorldHealthzResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["service"] = o.Service
	toSerialize["environment"] = o.Environment
	toSerialize["version"] = o.Version
	toSerialize["timestamp"] = o.Timestamp
	if !IsNil(o.Uptime) {
		toSerialize["uptime"] = o.Uptime
	}
	return toSerialize, nil
}

func (o *HelloWorldHealthzResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"service",
		"environment",
		"version",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelloWorldHealthzResponse := _HelloWorldHealthzResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelloWorldHealthzResponse)

	if err != nil {
		return err
	}

	*o = HelloWorldHealthzResponse(varHelloWorldHealthzResponse)

	return err
}

type NullableHelloWorldHealthzResponse struct {
	value *HelloWorldHealthzResponse
	isSet bool
}

func (v NullableHelloWorldHealthzResponse) Get() *HelloWorldHealthzResponse {
	return v.value
}

func (v *NullableHelloWorldHealthzResponse) Set(val *HelloWorldHealthzResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHelloWorldHealthzResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHelloWorldHealthzResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelloWorldHealthzResponse(val *HelloWorldHealthzResponse) *NullableHelloWorldHealthzResponse {
	return &NullableHelloWorldHealthzResponse{value: val, isSet: true}
}

func (v NullableHelloWorldHealthzResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelloWorldHealthzResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


