/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AiGatewayChatCompletionRequestResponseFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiGatewayChatCompletionRequestResponseFormat{}

// AiGatewayChatCompletionRequestResponseFormat Response format (text or json_object)
type AiGatewayChatCompletionRequestResponseFormat struct {
	Type string `json:"type"`
}

type _AiGatewayChatCompletionRequestResponseFormat AiGatewayChatCompletionRequestResponseFormat

// NewAiGatewayChatCompletionRequestResponseFormat instantiates a new AiGatewayChatCompletionRequestResponseFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiGatewayChatCompletionRequestResponseFormat(type_ string) *AiGatewayChatCompletionRequestResponseFormat {
	this := AiGatewayChatCompletionRequestResponseFormat{}
	this.Type = type_
	return &this
}

// NewAiGatewayChatCompletionRequestResponseFormatWithDefaults instantiates a new AiGatewayChatCompletionRequestResponseFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiGatewayChatCompletionRequestResponseFormatWithDefaults() *AiGatewayChatCompletionRequestResponseFormat {
	this := AiGatewayChatCompletionRequestResponseFormat{}
	return &this
}

// GetType returns the Type field value
func (o *AiGatewayChatCompletionRequestResponseFormat) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequestResponseFormat) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AiGatewayChatCompletionRequestResponseFormat) SetType(v string) {
	o.Type = v
}

func (o AiGatewayChatCompletionRequestResponseFormat) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiGatewayChatCompletionRequestResponseFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *AiGatewayChatCompletionRequestResponseFormat) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAiGatewayChatCompletionRequestResponseFormat := _AiGatewayChatCompletionRequestResponseFormat{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAiGatewayChatCompletionRequestResponseFormat)

	if err != nil {
		return err
	}

	*o = AiGatewayChatCompletionRequestResponseFormat(varAiGatewayChatCompletionRequestResponseFormat)

	return err
}

type NullableAiGatewayChatCompletionRequestResponseFormat struct {
	value *AiGatewayChatCompletionRequestResponseFormat
	isSet bool
}

func (v NullableAiGatewayChatCompletionRequestResponseFormat) Get() *AiGatewayChatCompletionRequestResponseFormat {
	return v.value
}

func (v *NullableAiGatewayChatCompletionRequestResponseFormat) Set(val *AiGatewayChatCompletionRequestResponseFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableAiGatewayChatCompletionRequestResponseFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableAiGatewayChatCompletionRequestResponseFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiGatewayChatCompletionRequestResponseFormat(val *AiGatewayChatCompletionRequestResponseFormat) *NullableAiGatewayChatCompletionRequestResponseFormat {
	return &NullableAiGatewayChatCompletionRequestResponseFormat{value: val, isSet: true}
}

func (v NullableAiGatewayChatCompletionRequestResponseFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiGatewayChatCompletionRequestResponseFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


