/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HelloWorldCreateMessageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelloWorldCreateMessageRequest{}

// HelloWorldCreateMessageRequest struct for HelloWorldCreateMessageRequest
type HelloWorldCreateMessageRequest struct {
	// Message content (1-500 characters)
	Message string `json:"message"`
	// Message priority level
	Priority *string `json:"priority,omitempty"`
}

type _HelloWorldCreateMessageRequest HelloWorldCreateMessageRequest

// NewHelloWorldCreateMessageRequest instantiates a new HelloWorldCreateMessageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelloWorldCreateMessageRequest(message string) *HelloWorldCreateMessageRequest {
	this := HelloWorldCreateMessageRequest{}
	this.Message = message
	return &this
}

// NewHelloWorldCreateMessageRequestWithDefaults instantiates a new HelloWorldCreateMessageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelloWorldCreateMessageRequestWithDefaults() *HelloWorldCreateMessageRequest {
	this := HelloWorldCreateMessageRequest{}
	return &this
}

// GetMessage returns the Message field value
func (o *HelloWorldCreateMessageRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *HelloWorldCreateMessageRequest) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *HelloWorldCreateMessageRequest) SetMessage(v string) {
	o.Message = v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *HelloWorldCreateMessageRequest) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelloWorldCreateMessageRequest) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *HelloWorldCreateMessageRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *HelloWorldCreateMessageRequest) SetPriority(v string) {
	o.Priority = &v
}

func (o HelloWorldCreateMessageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelloWorldCreateMessageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

func (o *HelloWorldCreateMessageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelloWorldCreateMessageRequest := _HelloWorldCreateMessageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelloWorldCreateMessageRequest)

	if err != nil {
		return err
	}

	*o = HelloWorldCreateMessageRequest(varHelloWorldCreateMessageRequest)

	return err
}

type NullableHelloWorldCreateMessageRequest struct {
	value *HelloWorldCreateMessageRequest
	isSet bool
}

func (v NullableHelloWorldCreateMessageRequest) Get() *HelloWorldCreateMessageRequest {
	return v.value
}

func (v *NullableHelloWorldCreateMessageRequest) Set(val *HelloWorldCreateMessageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHelloWorldCreateMessageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHelloWorldCreateMessageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelloWorldCreateMessageRequest(val *HelloWorldCreateMessageRequest) *NullableHelloWorldCreateMessageRequest {
	return &NullableHelloWorldCreateMessageRequest{value: val, isSet: true}
}

func (v NullableHelloWorldCreateMessageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelloWorldCreateMessageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


