/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstackplatform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HelloWorldErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelloWorldErrorResponse{}

// HelloWorldErrorResponse struct for HelloWorldErrorResponse
type HelloWorldErrorResponse struct {
	Error AiGatewayErrorResponseError `json:"error"`
}

type _HelloWorldErrorResponse HelloWorldErrorResponse

// NewHelloWorldErrorResponse instantiates a new HelloWorldErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelloWorldErrorResponse(error_ AiGatewayErrorResponseError) *HelloWorldErrorResponse {
	this := HelloWorldErrorResponse{}
	this.Error = error_
	return &this
}

// NewHelloWorldErrorResponseWithDefaults instantiates a new HelloWorldErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelloWorldErrorResponseWithDefaults() *HelloWorldErrorResponse {
	this := HelloWorldErrorResponse{}
	return &this
}

// GetError returns the Error field value
func (o *HelloWorldErrorResponse) GetError() AiGatewayErrorResponseError {
	if o == nil {
		var ret AiGatewayErrorResponseError
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *HelloWorldErrorResponse) GetErrorOk() (*AiGatewayErrorResponseError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *HelloWorldErrorResponse) SetError(v AiGatewayErrorResponseError) {
	o.Error = v
}

func (o HelloWorldErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelloWorldErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *HelloWorldErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelloWorldErrorResponse := _HelloWorldErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelloWorldErrorResponse)

	if err != nil {
		return err
	}

	*o = HelloWorldErrorResponse(varHelloWorldErrorResponse)

	return err
}

type NullableHelloWorldErrorResponse struct {
	value *HelloWorldErrorResponse
	isSet bool
}

func (v NullableHelloWorldErrorResponse) Get() *HelloWorldErrorResponse {
	return v.value
}

func (v *NullableHelloWorldErrorResponse) Set(val *HelloWorldErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHelloWorldErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHelloWorldErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelloWorldErrorResponse(val *HelloWorldErrorResponse) *NullableHelloWorldErrorResponse {
	return &NullableHelloWorldErrorResponse{value: val, isSet: true}
}

func (v NullableHelloWorldErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelloWorldErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


