/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the HelloWorldCreateMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelloWorldCreateMessageResponse{}

// HelloWorldCreateMessageResponse struct for HelloWorldCreateMessageResponse
type HelloWorldCreateMessageResponse struct {
	// Message ID
	Id string `json:"id"`
	// Message content
	Message string `json:"message"`
	// Message priority
	Priority string `json:"priority"`
	// Creation timestamp
	CreatedAt time.Time `json:"createdAt"`
}

type _HelloWorldCreateMessageResponse HelloWorldCreateMessageResponse

// NewHelloWorldCreateMessageResponse instantiates a new HelloWorldCreateMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelloWorldCreateMessageResponse(id string, message string, priority string, createdAt time.Time) *HelloWorldCreateMessageResponse {
	this := HelloWorldCreateMessageResponse{}
	this.Id = id
	this.Message = message
	this.Priority = priority
	this.CreatedAt = createdAt
	return &this
}

// NewHelloWorldCreateMessageResponseWithDefaults instantiates a new HelloWorldCreateMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelloWorldCreateMessageResponseWithDefaults() *HelloWorldCreateMessageResponse {
	this := HelloWorldCreateMessageResponse{}
	return &this
}

// GetId returns the Id field value
func (o *HelloWorldCreateMessageResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *HelloWorldCreateMessageResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *HelloWorldCreateMessageResponse) SetId(v string) {
	o.Id = v
}

// GetMessage returns the Message field value
func (o *HelloWorldCreateMessageResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *HelloWorldCreateMessageResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *HelloWorldCreateMessageResponse) SetMessage(v string) {
	o.Message = v
}

// GetPriority returns the Priority field value
func (o *HelloWorldCreateMessageResponse) GetPriority() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *HelloWorldCreateMessageResponse) GetPriorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *HelloWorldCreateMessageResponse) SetPriority(v string) {
	o.Priority = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *HelloWorldCreateMessageResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *HelloWorldCreateMessageResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *HelloWorldCreateMessageResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o HelloWorldCreateMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelloWorldCreateMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["message"] = o.Message
	toSerialize["priority"] = o.Priority
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *HelloWorldCreateMessageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"message",
		"priority",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelloWorldCreateMessageResponse := _HelloWorldCreateMessageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelloWorldCreateMessageResponse)

	if err != nil {
		return err
	}

	*o = HelloWorldCreateMessageResponse(varHelloWorldCreateMessageResponse)

	return err
}

type NullableHelloWorldCreateMessageResponse struct {
	value *HelloWorldCreateMessageResponse
	isSet bool
}

func (v NullableHelloWorldCreateMessageResponse) Get() *HelloWorldCreateMessageResponse {
	return v.value
}

func (v *NullableHelloWorldCreateMessageResponse) Set(val *HelloWorldCreateMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHelloWorldCreateMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHelloWorldCreateMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelloWorldCreateMessageResponse(val *HelloWorldCreateMessageResponse) *NullableHelloWorldCreateMessageResponse {
	return &NullableHelloWorldCreateMessageResponse{value: val, isSet: true}
}

func (v NullableHelloWorldCreateMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelloWorldCreateMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


