/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstackplatform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AiGatewayChatMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiGatewayChatMessage{}

// AiGatewayChatMessage struct for AiGatewayChatMessage
type AiGatewayChatMessage struct {
	Role string `json:"role"`
	Content NullableString `json:"content,omitempty"`
	Name *string `json:"name,omitempty"`
	ToolCalls []interface{} `json:"tool_calls,omitempty"`
	ToolCallId *string `json:"tool_call_id,omitempty"`
}

type _AiGatewayChatMessage AiGatewayChatMessage

// NewAiGatewayChatMessage instantiates a new AiGatewayChatMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiGatewayChatMessage(role string) *AiGatewayChatMessage {
	this := AiGatewayChatMessage{}
	this.Role = role
	return &this
}

// NewAiGatewayChatMessageWithDefaults instantiates a new AiGatewayChatMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiGatewayChatMessageWithDefaults() *AiGatewayChatMessage {
	this := AiGatewayChatMessage{}
	return &this
}

// GetRole returns the Role field value
func (o *AiGatewayChatMessage) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatMessage) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *AiGatewayChatMessage) SetRole(v string) {
	o.Role = v
}

// GetContent returns the Content field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiGatewayChatMessage) GetContent() string {
	if o == nil || IsNil(o.Content.Get()) {
		var ret string
		return ret
	}
	return *o.Content.Get()
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiGatewayChatMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Content.Get(), o.Content.IsSet()
}

// HasContent returns a boolean if a field has been set.
func (o *AiGatewayChatMessage) HasContent() bool {
	if o != nil && o.Content.IsSet() {
		return true
	}

	return false
}

// SetContent gets a reference to the given NullableString and assigns it to the Content field.
func (o *AiGatewayChatMessage) SetContent(v string) {
	o.Content.Set(&v)
}
// SetContentNil sets the value for Content to be an explicit nil
func (o *AiGatewayChatMessage) SetContentNil() {
	o.Content.Set(nil)
}

// UnsetContent ensures that no value is present for Content, not even an explicit nil
func (o *AiGatewayChatMessage) UnsetContent() {
	o.Content.Unset()
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AiGatewayChatMessage) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatMessage) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AiGatewayChatMessage) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AiGatewayChatMessage) SetName(v string) {
	o.Name = &v
}

// GetToolCalls returns the ToolCalls field value if set, zero value otherwise.
func (o *AiGatewayChatMessage) GetToolCalls() []interface{} {
	if o == nil || IsNil(o.ToolCalls) {
		var ret []interface{}
		return ret
	}
	return o.ToolCalls
}

// GetToolCallsOk returns a tuple with the ToolCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatMessage) GetToolCallsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.ToolCalls) {
		return nil, false
	}
	return o.ToolCalls, true
}

// HasToolCalls returns a boolean if a field has been set.
func (o *AiGatewayChatMessage) HasToolCalls() bool {
	if o != nil && !IsNil(o.ToolCalls) {
		return true
	}

	return false
}

// SetToolCalls gets a reference to the given []interface{} and assigns it to the ToolCalls field.
func (o *AiGatewayChatMessage) SetToolCalls(v []interface{}) {
	o.ToolCalls = v
}

// GetToolCallId returns the ToolCallId field value if set, zero value otherwise.
func (o *AiGatewayChatMessage) GetToolCallId() string {
	if o == nil || IsNil(o.ToolCallId) {
		var ret string
		return ret
	}
	return *o.ToolCallId
}

// GetToolCallIdOk returns a tuple with the ToolCallId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatMessage) GetToolCallIdOk() (*string, bool) {
	if o == nil || IsNil(o.ToolCallId) {
		return nil, false
	}
	return o.ToolCallId, true
}

// HasToolCallId returns a boolean if a field has been set.
func (o *AiGatewayChatMessage) HasToolCallId() bool {
	if o != nil && !IsNil(o.ToolCallId) {
		return true
	}

	return false
}

// SetToolCallId gets a reference to the given string and assigns it to the ToolCallId field.
func (o *AiGatewayChatMessage) SetToolCallId(v string) {
	o.ToolCallId = &v
}

func (o AiGatewayChatMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiGatewayChatMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	if o.Content.IsSet() {
		toSerialize["content"] = o.Content.Get()
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ToolCalls) {
		toSerialize["tool_calls"] = o.ToolCalls
	}
	if !IsNil(o.ToolCallId) {
		toSerialize["tool_call_id"] = o.ToolCallId
	}
	return toSerialize, nil
}

func (o *AiGatewayChatMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAiGatewayChatMessage := _AiGatewayChatMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAiGatewayChatMessage)

	if err != nil {
		return err
	}

	*o = AiGatewayChatMessage(varAiGatewayChatMessage)

	return err
}

type NullableAiGatewayChatMessage struct {
	value *AiGatewayChatMessage
	isSet bool
}

func (v NullableAiGatewayChatMessage) Get() *AiGatewayChatMessage {
	return v.value
}

func (v *NullableAiGatewayChatMessage) Set(val *AiGatewayChatMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableAiGatewayChatMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableAiGatewayChatMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiGatewayChatMessage(val *AiGatewayChatMessage) *NullableAiGatewayChatMessage {
	return &NullableAiGatewayChatMessage{value: val, isSet: true}
}

func (v NullableAiGatewayChatMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiGatewayChatMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


