/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AiGatewayChatCompletionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiGatewayChatCompletionRequest{}

// AiGatewayChatCompletionRequest struct for AiGatewayChatCompletionRequest
type AiGatewayChatCompletionRequest struct {
	// Model to use (e.g., \"openai/gpt-4\", \"anthropic/claude-3-5-sonnet-20241022\")
	Model string `json:"model"`
	// Array of messages in the conversation
	Messages []AiGatewayChatMessage `json:"messages"`
	// Sampling temperature (0-2)
	Temperature *float32 `json:"temperature,omitempty"`
	// Nucleus sampling parameter
	TopP *float32 `json:"top_p,omitempty"`
	// Number of completions to generate
	N *int32 `json:"n,omitempty"`
	// Whether to stream responses
	Stream *bool `json:"stream,omitempty"`
	Stop *AiGatewayChatCompletionRequestStop `json:"stop,omitempty"`
	// Maximum tokens to generate
	MaxTokens *int32 `json:"max_tokens,omitempty"`
	// Presence penalty (-2 to 2)
	PresencePenalty *float32 `json:"presence_penalty,omitempty"`
	// Frequency penalty (-2 to 2)
	FrequencyPenalty *float32 `json:"frequency_penalty,omitempty"`
	// Token logit bias
	LogitBias map[string]float32 `json:"logit_bias,omitempty"`
	// Unique user identifier
	User *string `json:"user,omitempty"`
	// Tools available for the model to call
	Tools []interface{} `json:"tools,omitempty"`
	ToolChoice NullableString `json:"tool_choice,omitempty"`
	ResponseFormat *AiGatewayChatCompletionRequestResponseFormat `json:"response_format,omitempty"`
	// Random seed for deterministic sampling
	Seed *int32 `json:"seed,omitempty"`
}

type _AiGatewayChatCompletionRequest AiGatewayChatCompletionRequest

// NewAiGatewayChatCompletionRequest instantiates a new AiGatewayChatCompletionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiGatewayChatCompletionRequest(model string, messages []AiGatewayChatMessage) *AiGatewayChatCompletionRequest {
	this := AiGatewayChatCompletionRequest{}
	this.Model = model
	this.Messages = messages
	return &this
}

// NewAiGatewayChatCompletionRequestWithDefaults instantiates a new AiGatewayChatCompletionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiGatewayChatCompletionRequestWithDefaults() *AiGatewayChatCompletionRequest {
	this := AiGatewayChatCompletionRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *AiGatewayChatCompletionRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *AiGatewayChatCompletionRequest) SetModel(v string) {
	o.Model = v
}

// GetMessages returns the Messages field value
func (o *AiGatewayChatCompletionRequest) GetMessages() []AiGatewayChatMessage {
	if o == nil {
		var ret []AiGatewayChatMessage
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetMessagesOk() ([]AiGatewayChatMessage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *AiGatewayChatCompletionRequest) SetMessages(v []AiGatewayChatMessage) {
	o.Messages = v
}

// GetTemperature returns the Temperature field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetTemperature() float32 {
	if o == nil || IsNil(o.Temperature) {
		var ret float32
		return ret
	}
	return *o.Temperature
}

// GetTemperatureOk returns a tuple with the Temperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetTemperatureOk() (*float32, bool) {
	if o == nil || IsNil(o.Temperature) {
		return nil, false
	}
	return o.Temperature, true
}

// HasTemperature returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasTemperature() bool {
	if o != nil && !IsNil(o.Temperature) {
		return true
	}

	return false
}

// SetTemperature gets a reference to the given float32 and assigns it to the Temperature field.
func (o *AiGatewayChatCompletionRequest) SetTemperature(v float32) {
	o.Temperature = &v
}

// GetTopP returns the TopP field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetTopP() float32 {
	if o == nil || IsNil(o.TopP) {
		var ret float32
		return ret
	}
	return *o.TopP
}

// GetTopPOk returns a tuple with the TopP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetTopPOk() (*float32, bool) {
	if o == nil || IsNil(o.TopP) {
		return nil, false
	}
	return o.TopP, true
}

// HasTopP returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasTopP() bool {
	if o != nil && !IsNil(o.TopP) {
		return true
	}

	return false
}

// SetTopP gets a reference to the given float32 and assigns it to the TopP field.
func (o *AiGatewayChatCompletionRequest) SetTopP(v float32) {
	o.TopP = &v
}

// GetN returns the N field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetN() int32 {
	if o == nil || IsNil(o.N) {
		var ret int32
		return ret
	}
	return *o.N
}

// GetNOk returns a tuple with the N field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetNOk() (*int32, bool) {
	if o == nil || IsNil(o.N) {
		return nil, false
	}
	return o.N, true
}

// HasN returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasN() bool {
	if o != nil && !IsNil(o.N) {
		return true
	}

	return false
}

// SetN gets a reference to the given int32 and assigns it to the N field.
func (o *AiGatewayChatCompletionRequest) SetN(v int32) {
	o.N = &v
}

// GetStream returns the Stream field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetStream() bool {
	if o == nil || IsNil(o.Stream) {
		var ret bool
		return ret
	}
	return *o.Stream
}

// GetStreamOk returns a tuple with the Stream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetStreamOk() (*bool, bool) {
	if o == nil || IsNil(o.Stream) {
		return nil, false
	}
	return o.Stream, true
}

// HasStream returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasStream() bool {
	if o != nil && !IsNil(o.Stream) {
		return true
	}

	return false
}

// SetStream gets a reference to the given bool and assigns it to the Stream field.
func (o *AiGatewayChatCompletionRequest) SetStream(v bool) {
	o.Stream = &v
}

// GetStop returns the Stop field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetStop() AiGatewayChatCompletionRequestStop {
	if o == nil || IsNil(o.Stop) {
		var ret AiGatewayChatCompletionRequestStop
		return ret
	}
	return *o.Stop
}

// GetStopOk returns a tuple with the Stop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetStopOk() (*AiGatewayChatCompletionRequestStop, bool) {
	if o == nil || IsNil(o.Stop) {
		return nil, false
	}
	return o.Stop, true
}

// HasStop returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasStop() bool {
	if o != nil && !IsNil(o.Stop) {
		return true
	}

	return false
}

// SetStop gets a reference to the given AiGatewayChatCompletionRequestStop and assigns it to the Stop field.
func (o *AiGatewayChatCompletionRequest) SetStop(v AiGatewayChatCompletionRequestStop) {
	o.Stop = &v
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens) {
		var ret int32
		return ret
	}
	return *o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokens) {
		return nil, false
	}
	return o.MaxTokens, true
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasMaxTokens() bool {
	if o != nil && !IsNil(o.MaxTokens) {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given int32 and assigns it to the MaxTokens field.
func (o *AiGatewayChatCompletionRequest) SetMaxTokens(v int32) {
	o.MaxTokens = &v
}

// GetPresencePenalty returns the PresencePenalty field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetPresencePenalty() float32 {
	if o == nil || IsNil(o.PresencePenalty) {
		var ret float32
		return ret
	}
	return *o.PresencePenalty
}

// GetPresencePenaltyOk returns a tuple with the PresencePenalty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetPresencePenaltyOk() (*float32, bool) {
	if o == nil || IsNil(o.PresencePenalty) {
		return nil, false
	}
	return o.PresencePenalty, true
}

// HasPresencePenalty returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasPresencePenalty() bool {
	if o != nil && !IsNil(o.PresencePenalty) {
		return true
	}

	return false
}

// SetPresencePenalty gets a reference to the given float32 and assigns it to the PresencePenalty field.
func (o *AiGatewayChatCompletionRequest) SetPresencePenalty(v float32) {
	o.PresencePenalty = &v
}

// GetFrequencyPenalty returns the FrequencyPenalty field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetFrequencyPenalty() float32 {
	if o == nil || IsNil(o.FrequencyPenalty) {
		var ret float32
		return ret
	}
	return *o.FrequencyPenalty
}

// GetFrequencyPenaltyOk returns a tuple with the FrequencyPenalty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetFrequencyPenaltyOk() (*float32, bool) {
	if o == nil || IsNil(o.FrequencyPenalty) {
		return nil, false
	}
	return o.FrequencyPenalty, true
}

// HasFrequencyPenalty returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasFrequencyPenalty() bool {
	if o != nil && !IsNil(o.FrequencyPenalty) {
		return true
	}

	return false
}

// SetFrequencyPenalty gets a reference to the given float32 and assigns it to the FrequencyPenalty field.
func (o *AiGatewayChatCompletionRequest) SetFrequencyPenalty(v float32) {
	o.FrequencyPenalty = &v
}

// GetLogitBias returns the LogitBias field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetLogitBias() map[string]float32 {
	if o == nil || IsNil(o.LogitBias) {
		var ret map[string]float32
		return ret
	}
	return o.LogitBias
}

// GetLogitBiasOk returns a tuple with the LogitBias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetLogitBiasOk() (map[string]float32, bool) {
	if o == nil || IsNil(o.LogitBias) {
		return map[string]float32{}, false
	}
	return o.LogitBias, true
}

// HasLogitBias returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasLogitBias() bool {
	if o != nil && !IsNil(o.LogitBias) {
		return true
	}

	return false
}

// SetLogitBias gets a reference to the given map[string]float32 and assigns it to the LogitBias field.
func (o *AiGatewayChatCompletionRequest) SetLogitBias(v map[string]float32) {
	o.LogitBias = v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *AiGatewayChatCompletionRequest) SetUser(v string) {
	o.User = &v
}

// GetTools returns the Tools field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetTools() []interface{} {
	if o == nil || IsNil(o.Tools) {
		var ret []interface{}
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetToolsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []interface{} and assigns it to the Tools field.
func (o *AiGatewayChatCompletionRequest) SetTools(v []interface{}) {
	o.Tools = v
}

// GetToolChoice returns the ToolChoice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AiGatewayChatCompletionRequest) GetToolChoice() string {
	if o == nil || IsNil(o.ToolChoice.Get()) {
		var ret string
		return ret
	}
	return *o.ToolChoice.Get()
}

// GetToolChoiceOk returns a tuple with the ToolChoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AiGatewayChatCompletionRequest) GetToolChoiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ToolChoice.Get(), o.ToolChoice.IsSet()
}

// HasToolChoice returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasToolChoice() bool {
	if o != nil && o.ToolChoice.IsSet() {
		return true
	}

	return false
}

// SetToolChoice gets a reference to the given NullableString and assigns it to the ToolChoice field.
func (o *AiGatewayChatCompletionRequest) SetToolChoice(v string) {
	o.ToolChoice.Set(&v)
}
// SetToolChoiceNil sets the value for ToolChoice to be an explicit nil
func (o *AiGatewayChatCompletionRequest) SetToolChoiceNil() {
	o.ToolChoice.Set(nil)
}

// UnsetToolChoice ensures that no value is present for ToolChoice, not even an explicit nil
func (o *AiGatewayChatCompletionRequest) UnsetToolChoice() {
	o.ToolChoice.Unset()
}

// GetResponseFormat returns the ResponseFormat field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetResponseFormat() AiGatewayChatCompletionRequestResponseFormat {
	if o == nil || IsNil(o.ResponseFormat) {
		var ret AiGatewayChatCompletionRequestResponseFormat
		return ret
	}
	return *o.ResponseFormat
}

// GetResponseFormatOk returns a tuple with the ResponseFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetResponseFormatOk() (*AiGatewayChatCompletionRequestResponseFormat, bool) {
	if o == nil || IsNil(o.ResponseFormat) {
		return nil, false
	}
	return o.ResponseFormat, true
}

// HasResponseFormat returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasResponseFormat() bool {
	if o != nil && !IsNil(o.ResponseFormat) {
		return true
	}

	return false
}

// SetResponseFormat gets a reference to the given AiGatewayChatCompletionRequestResponseFormat and assigns it to the ResponseFormat field.
func (o *AiGatewayChatCompletionRequest) SetResponseFormat(v AiGatewayChatCompletionRequestResponseFormat) {
	o.ResponseFormat = &v
}

// GetSeed returns the Seed field value if set, zero value otherwise.
func (o *AiGatewayChatCompletionRequest) GetSeed() int32 {
	if o == nil || IsNil(o.Seed) {
		var ret int32
		return ret
	}
	return *o.Seed
}

// GetSeedOk returns a tuple with the Seed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionRequest) GetSeedOk() (*int32, bool) {
	if o == nil || IsNil(o.Seed) {
		return nil, false
	}
	return o.Seed, true
}

// HasSeed returns a boolean if a field has been set.
func (o *AiGatewayChatCompletionRequest) HasSeed() bool {
	if o != nil && !IsNil(o.Seed) {
		return true
	}

	return false
}

// SetSeed gets a reference to the given int32 and assigns it to the Seed field.
func (o *AiGatewayChatCompletionRequest) SetSeed(v int32) {
	o.Seed = &v
}

func (o AiGatewayChatCompletionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiGatewayChatCompletionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["model"] = o.Model
	toSerialize["messages"] = o.Messages
	if !IsNil(o.Temperature) {
		toSerialize["temperature"] = o.Temperature
	}
	if !IsNil(o.TopP) {
		toSerialize["top_p"] = o.TopP
	}
	if !IsNil(o.N) {
		toSerialize["n"] = o.N
	}
	if !IsNil(o.Stream) {
		toSerialize["stream"] = o.Stream
	}
	if !IsNil(o.Stop) {
		toSerialize["stop"] = o.Stop
	}
	if !IsNil(o.MaxTokens) {
		toSerialize["max_tokens"] = o.MaxTokens
	}
	if !IsNil(o.PresencePenalty) {
		toSerialize["presence_penalty"] = o.PresencePenalty
	}
	if !IsNil(o.FrequencyPenalty) {
		toSerialize["frequency_penalty"] = o.FrequencyPenalty
	}
	if !IsNil(o.LogitBias) {
		toSerialize["logit_bias"] = o.LogitBias
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Tools) {
		toSerialize["tools"] = o.Tools
	}
	if o.ToolChoice.IsSet() {
		toSerialize["tool_choice"] = o.ToolChoice.Get()
	}
	if !IsNil(o.ResponseFormat) {
		toSerialize["response_format"] = o.ResponseFormat
	}
	if !IsNil(o.Seed) {
		toSerialize["seed"] = o.Seed
	}
	return toSerialize, nil
}

func (o *AiGatewayChatCompletionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"model",
		"messages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAiGatewayChatCompletionRequest := _AiGatewayChatCompletionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAiGatewayChatCompletionRequest)

	if err != nil {
		return err
	}

	*o = AiGatewayChatCompletionRequest(varAiGatewayChatCompletionRequest)

	return err
}

type NullableAiGatewayChatCompletionRequest struct {
	value *AiGatewayChatCompletionRequest
	isSet bool
}

func (v NullableAiGatewayChatCompletionRequest) Get() *AiGatewayChatCompletionRequest {
	return v.value
}

func (v *NullableAiGatewayChatCompletionRequest) Set(val *AiGatewayChatCompletionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAiGatewayChatCompletionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAiGatewayChatCompletionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiGatewayChatCompletionRequest(val *AiGatewayChatCompletionRequest) *NullableAiGatewayChatCompletionRequest {
	return &NullableAiGatewayChatCompletionRequest{value: val, isSet: true}
}

func (v NullableAiGatewayChatCompletionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiGatewayChatCompletionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


