/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the HelloWorldHelloResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelloWorldHelloResponse{}

// HelloWorldHelloResponse struct for HelloWorldHelloResponse
type HelloWorldHelloResponse struct {
	// Greeting message
	Message string `json:"message"`
	// Service name
	Service string `json:"service"`
	// Environment (development/staging/production)
	Environment string `json:"environment"`
	// ISO 8601 timestamp
	Timestamp time.Time `json:"timestamp"`
	// Service version
	Version string `json:"version"`
}

type _HelloWorldHelloResponse HelloWorldHelloResponse

// NewHelloWorldHelloResponse instantiates a new HelloWorldHelloResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelloWorldHelloResponse(message string, service string, environment string, timestamp time.Time, version string) *HelloWorldHelloResponse {
	this := HelloWorldHelloResponse{}
	this.Message = message
	this.Service = service
	this.Environment = environment
	this.Timestamp = timestamp
	this.Version = version
	return &this
}

// NewHelloWorldHelloResponseWithDefaults instantiates a new HelloWorldHelloResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelloWorldHelloResponseWithDefaults() *HelloWorldHelloResponse {
	this := HelloWorldHelloResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *HelloWorldHelloResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *HelloWorldHelloResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *HelloWorldHelloResponse) SetMessage(v string) {
	o.Message = v
}

// GetService returns the Service field value
func (o *HelloWorldHelloResponse) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *HelloWorldHelloResponse) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *HelloWorldHelloResponse) SetService(v string) {
	o.Service = v
}

// GetEnvironment returns the Environment field value
func (o *HelloWorldHelloResponse) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *HelloWorldHelloResponse) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *HelloWorldHelloResponse) SetEnvironment(v string) {
	o.Environment = v
}

// GetTimestamp returns the Timestamp field value
func (o *HelloWorldHelloResponse) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *HelloWorldHelloResponse) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *HelloWorldHelloResponse) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetVersion returns the Version field value
func (o *HelloWorldHelloResponse) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *HelloWorldHelloResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *HelloWorldHelloResponse) SetVersion(v string) {
	o.Version = v
}

func (o HelloWorldHelloResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelloWorldHelloResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["service"] = o.Service
	toSerialize["environment"] = o.Environment
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *HelloWorldHelloResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"service",
		"environment",
		"timestamp",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelloWorldHelloResponse := _HelloWorldHelloResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelloWorldHelloResponse)

	if err != nil {
		return err
	}

	*o = HelloWorldHelloResponse(varHelloWorldHelloResponse)

	return err
}

type NullableHelloWorldHelloResponse struct {
	value *HelloWorldHelloResponse
	isSet bool
}

func (v NullableHelloWorldHelloResponse) Get() *HelloWorldHelloResponse {
	return v.value
}

func (v *NullableHelloWorldHelloResponse) Set(val *HelloWorldHelloResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHelloWorldHelloResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHelloWorldHelloResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelloWorldHelloResponse(val *HelloWorldHelloResponse) *NullableHelloWorldHelloResponse {
	return &NullableHelloWorldHelloResponse{value: val, isSet: true}
}

func (v NullableHelloWorldHelloResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelloWorldHelloResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


