/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AiGatewayErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiGatewayErrorResponse{}

// AiGatewayErrorResponse struct for AiGatewayErrorResponse
type AiGatewayErrorResponse struct {
	Error AiGatewayErrorResponseError `json:"error"`
}

type _AiGatewayErrorResponse AiGatewayErrorResponse

// NewAiGatewayErrorResponse instantiates a new AiGatewayErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiGatewayErrorResponse(error_ AiGatewayErrorResponseError) *AiGatewayErrorResponse {
	this := AiGatewayErrorResponse{}
	this.Error = error_
	return &this
}

// NewAiGatewayErrorResponseWithDefaults instantiates a new AiGatewayErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiGatewayErrorResponseWithDefaults() *AiGatewayErrorResponse {
	this := AiGatewayErrorResponse{}
	return &this
}

// GetError returns the Error field value
func (o *AiGatewayErrorResponse) GetError() AiGatewayErrorResponseError {
	if o == nil {
		var ret AiGatewayErrorResponseError
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *AiGatewayErrorResponse) GetErrorOk() (*AiGatewayErrorResponseError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *AiGatewayErrorResponse) SetError(v AiGatewayErrorResponseError) {
	o.Error = v
}

func (o AiGatewayErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiGatewayErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *AiGatewayErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAiGatewayErrorResponse := _AiGatewayErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAiGatewayErrorResponse)

	if err != nil {
		return err
	}

	*o = AiGatewayErrorResponse(varAiGatewayErrorResponse)

	return err
}

type NullableAiGatewayErrorResponse struct {
	value *AiGatewayErrorResponse
	isSet bool
}

func (v NullableAiGatewayErrorResponse) Get() *AiGatewayErrorResponse {
	return v.value
}

func (v *NullableAiGatewayErrorResponse) Set(val *AiGatewayErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAiGatewayErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAiGatewayErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiGatewayErrorResponse(val *AiGatewayErrorResponse) *NullableAiGatewayErrorResponse {
	return &NullableAiGatewayErrorResponse{value: val, isSet: true}
}

func (v NullableAiGatewayErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiGatewayErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


