/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AiGatewayChatCompletionResponseUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiGatewayChatCompletionResponseUsage{}

// AiGatewayChatCompletionResponseUsage struct for AiGatewayChatCompletionResponseUsage
type AiGatewayChatCompletionResponseUsage struct {
	PromptTokens int32 `json:"prompt_tokens"`
	CompletionTokens int32 `json:"completion_tokens"`
	TotalTokens int32 `json:"total_tokens"`
}

type _AiGatewayChatCompletionResponseUsage AiGatewayChatCompletionResponseUsage

// NewAiGatewayChatCompletionResponseUsage instantiates a new AiGatewayChatCompletionResponseUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiGatewayChatCompletionResponseUsage(promptTokens int32, completionTokens int32, totalTokens int32) *AiGatewayChatCompletionResponseUsage {
	this := AiGatewayChatCompletionResponseUsage{}
	this.PromptTokens = promptTokens
	this.CompletionTokens = completionTokens
	this.TotalTokens = totalTokens
	return &this
}

// NewAiGatewayChatCompletionResponseUsageWithDefaults instantiates a new AiGatewayChatCompletionResponseUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiGatewayChatCompletionResponseUsageWithDefaults() *AiGatewayChatCompletionResponseUsage {
	this := AiGatewayChatCompletionResponseUsage{}
	return &this
}

// GetPromptTokens returns the PromptTokens field value
func (o *AiGatewayChatCompletionResponseUsage) GetPromptTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PromptTokens
}

// GetPromptTokensOk returns a tuple with the PromptTokens field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponseUsage) GetPromptTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PromptTokens, true
}

// SetPromptTokens sets field value
func (o *AiGatewayChatCompletionResponseUsage) SetPromptTokens(v int32) {
	o.PromptTokens = v
}

// GetCompletionTokens returns the CompletionTokens field value
func (o *AiGatewayChatCompletionResponseUsage) GetCompletionTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CompletionTokens
}

// GetCompletionTokensOk returns a tuple with the CompletionTokens field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponseUsage) GetCompletionTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompletionTokens, true
}

// SetCompletionTokens sets field value
func (o *AiGatewayChatCompletionResponseUsage) SetCompletionTokens(v int32) {
	o.CompletionTokens = v
}

// GetTotalTokens returns the TotalTokens field value
func (o *AiGatewayChatCompletionResponseUsage) GetTotalTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalTokens
}

// GetTotalTokensOk returns a tuple with the TotalTokens field value
// and a boolean to check if the value has been set.
func (o *AiGatewayChatCompletionResponseUsage) GetTotalTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalTokens, true
}

// SetTotalTokens sets field value
func (o *AiGatewayChatCompletionResponseUsage) SetTotalTokens(v int32) {
	o.TotalTokens = v
}

func (o AiGatewayChatCompletionResponseUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiGatewayChatCompletionResponseUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prompt_tokens"] = o.PromptTokens
	toSerialize["completion_tokens"] = o.CompletionTokens
	toSerialize["total_tokens"] = o.TotalTokens
	return toSerialize, nil
}

func (o *AiGatewayChatCompletionResponseUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prompt_tokens",
		"completion_tokens",
		"total_tokens",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAiGatewayChatCompletionResponseUsage := _AiGatewayChatCompletionResponseUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAiGatewayChatCompletionResponseUsage)

	if err != nil {
		return err
	}

	*o = AiGatewayChatCompletionResponseUsage(varAiGatewayChatCompletionResponseUsage)

	return err
}

type NullableAiGatewayChatCompletionResponseUsage struct {
	value *AiGatewayChatCompletionResponseUsage
	isSet bool
}

func (v NullableAiGatewayChatCompletionResponseUsage) Get() *AiGatewayChatCompletionResponseUsage {
	return v.value
}

func (v *NullableAiGatewayChatCompletionResponseUsage) Set(val *AiGatewayChatCompletionResponseUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableAiGatewayChatCompletionResponseUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableAiGatewayChatCompletionResponseUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiGatewayChatCompletionResponseUsage(val *AiGatewayChatCompletionResponseUsage) *NullableAiGatewayChatCompletionResponseUsage {
	return &NullableAiGatewayChatCompletionResponseUsage{value: val, isSet: true}
}

func (v NullableAiGatewayChatCompletionResponseUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiGatewayChatCompletionResponseUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


