/*
BriskStack Platform API

Unified API for all BriskStack platform services

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package briskstack

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the HelloWorldProtectedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelloWorldProtectedResponse{}

// HelloWorldProtectedResponse struct for HelloWorldProtectedResponse
type HelloWorldProtectedResponse struct {
	// Success message
	Message string `json:"message"`
	// Authenticated user or service ID (from auth.sub)
	UserId string `json:"userId"`
	// User roles or service scopes (from auth.roles)
	Roles []string `json:"roles"`
	// ISO 8601 timestamp
	Timestamp time.Time `json:"timestamp"`
}

type _HelloWorldProtectedResponse HelloWorldProtectedResponse

// NewHelloWorldProtectedResponse instantiates a new HelloWorldProtectedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelloWorldProtectedResponse(message string, userId string, roles []string, timestamp time.Time) *HelloWorldProtectedResponse {
	this := HelloWorldProtectedResponse{}
	this.Message = message
	this.UserId = userId
	this.Roles = roles
	this.Timestamp = timestamp
	return &this
}

// NewHelloWorldProtectedResponseWithDefaults instantiates a new HelloWorldProtectedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelloWorldProtectedResponseWithDefaults() *HelloWorldProtectedResponse {
	this := HelloWorldProtectedResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *HelloWorldProtectedResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *HelloWorldProtectedResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *HelloWorldProtectedResponse) SetMessage(v string) {
	o.Message = v
}

// GetUserId returns the UserId field value
func (o *HelloWorldProtectedResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *HelloWorldProtectedResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *HelloWorldProtectedResponse) SetUserId(v string) {
	o.UserId = v
}

// GetRoles returns the Roles field value
func (o *HelloWorldProtectedResponse) GetRoles() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *HelloWorldProtectedResponse) GetRolesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *HelloWorldProtectedResponse) SetRoles(v []string) {
	o.Roles = v
}

// GetTimestamp returns the Timestamp field value
func (o *HelloWorldProtectedResponse) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *HelloWorldProtectedResponse) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *HelloWorldProtectedResponse) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

func (o HelloWorldProtectedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelloWorldProtectedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["userId"] = o.UserId
	toSerialize["roles"] = o.Roles
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *HelloWorldProtectedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"userId",
		"roles",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelloWorldProtectedResponse := _HelloWorldProtectedResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelloWorldProtectedResponse)

	if err != nil {
		return err
	}

	*o = HelloWorldProtectedResponse(varHelloWorldProtectedResponse)

	return err
}

type NullableHelloWorldProtectedResponse struct {
	value *HelloWorldProtectedResponse
	isSet bool
}

func (v NullableHelloWorldProtectedResponse) Get() *HelloWorldProtectedResponse {
	return v.value
}

func (v *NullableHelloWorldProtectedResponse) Set(val *HelloWorldProtectedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHelloWorldProtectedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHelloWorldProtectedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelloWorldProtectedResponse(val *HelloWorldProtectedResponse) *NullableHelloWorldProtectedResponse {
	return &NullableHelloWorldProtectedResponse{value: val, isSet: true}
}

func (v NullableHelloWorldProtectedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelloWorldProtectedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


